# Hack to infer an english description from another language.
# This is obviously a bad idea. This should be translated...

PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

CONSTRUCT 
{
  ?solution dct:description ?fake_en_desc .
}
WHERE
{ 
  ?solution a dcat:Dataset .
  ?solution dct:description ?description .
  OPTIONAL {
    ?solution dct:description ?desc_filter .
    FILTER langMatches( lang(?desc_filter), "en" )
  }
  FILTER (!BOUND(?desc_filter))
  BIND(STRLANG(STR(?description), "en") as ?fake_en_desc)


  #OPTIONAL {
  #  ?solution dct:publisher ?publisher .
  #}
  #FILTER (!bound(?publisher)) .
  #BIND(URI(CONCAT(STR( ?solution ), "/publisher"))  AS ?publisher_uri ) .
}
